// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBstYiwZUPYLUUcueu-oziZTFUD8Sftg_A',
    appId: '1:820487441803:web:4e3b80e1e0f17c0276b38e',
    messagingSenderId: '820487441803',
    projectId: 'socialmedia-5d2fd',
    authDomain: 'socialmedia-5d2fd.firebaseapp.com',
    storageBucket: 'socialmedia-5d2fd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsqJlrnl58Z_4jg_gc6eOhALhWYeaG1a0',
    appId: '1:820487441803:android:77cb8487fcb50a9576b38e',
    messagingSenderId: '820487441803',
    projectId: 'socialmedia-5d2fd',
    storageBucket: 'socialmedia-5d2fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvp_jaT6Cs9NMyhamzUCe7JXFcStgB5xA',
    appId: '1:820487441803:ios:8c9e6be275e130bd76b38e',
    messagingSenderId: '820487441803',
    projectId: 'socialmedia-5d2fd',
    storageBucket: 'socialmedia-5d2fd.firebasestorage.app',
    iosBundleId: 'com.sergy.socialMedia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvp_jaT6Cs9NMyhamzUCe7JXFcStgB5xA',
    appId: '1:820487441803:ios:8c9e6be275e130bd76b38e',
    messagingSenderId: '820487441803',
    projectId: 'socialmedia-5d2fd',
    storageBucket: 'socialmedia-5d2fd.firebasestorage.app',
    iosBundleId: 'com.sergy.socialMedia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBstYiwZUPYLUUcueu-oziZTFUD8Sftg_A',
    appId: '1:820487441803:web:2b25527a76c617ff76b38e',
    messagingSenderId: '820487441803',
    projectId: 'socialmedia-5d2fd',
    authDomain: 'socialmedia-5d2fd.firebaseapp.com',
    storageBucket: 'socialmedia-5d2fd.firebasestorage.app',
  );

}